### PR TITLE
To fix the compiling error of std c++11 and the change of Caffe2 shared library name.

### PR DESCRIPTION
**Pull request by teyenliu**
1. Add CMAKE_CXX_FLAGS for setting up C++11 standard
2. Fixe the library name of CAFFE2_LIB and CAFFE2_GPU_LIB

### CODE REVIEW

**Comment by leonardvandriel** [comment]
Hi @teyenliu, thanks for improving the cmake setup. It seems this works on macOS, but fails on Ubuntu:

```
CMake Error at CMakeLists.txt:30 (message):
  Caffe2 lib not found


-- Configuring incomplete, errors occurred!
See also "/home/dnpgu/caffe2_cpp_tutorial/build/CMakeFiles/CMakeOutput.log".
See also "/home/dnpgu/caffe2_cpp_tutorial/build/CMakeFiles/CMakeError.log".
make[1]: Entering directory '/home/dnpgu/caffe2_cpp_tutorial/build'
make[1]: *** No targets specified and no makefile found.  Stop.
make[1]: Leaving directory '/home/dnpgu/caffe2_cpp_tutorial/build'
Makefile:4: recipe for target 'all' failed
make: *** [all] Error 2
```

Did you get a chance to test it on Ubuntu?

Also, you included the `-g` flag, but isn't it better to specify this using CMake's `CMAKE_BUILD_TYPE`?

**Comment by teyenliu** [comment]
Hi @leonardvandriel , thanks for your response. 
Actually, it works on my Ubuntu 14.04. For macOS, I didn't have the environment to test.
About "-g" flag, you are right, it is better to use CMAKE_BUILD_TYPE.

**Comment by leonardvandriel** [comment]
I'm running Ubuntu 16.04. Perhaps that causes the difference in behavior. What happens when you run `find /usr -iname "libcaffe2*"`? For me it lists the two libs:

/usr/local/lib/libCaffe2_GPU.so
/usr/local/lib/libCaffe2_CPU.so

**Comment by leonardvandriel** [comment]
Also, adding the `-std=c++11` causes the error:

```
[ 39%] Building NVCC (Device) object CMakeFiles/caffe2_cpp_gpu.dir/src/caffe2/operator/caffe2_cpp_gpu_generated_diagonal_op.cu.o
nvcc fatal   : redefinition of argument 'std'
CMake Error at caffe2_cpp_gpu_generated_diagonal_op.cu.o.cmake:207 (message):
  Error generating
  /home/dnpgu/caffe2_cpp_tutorial/build/CMakeFiles/caffe2_cpp_gpu.dir/src/caffe2/operator/./caffe2_cpp_gpu_generated_diagonal_op.cu.o
```

**Comment by teyenliu** [comment]
I pulled the newest Caffe2 code in the master branch and then found that "libCaffe2_CPU.so" and "libCaffe2_GPU.so" won't be generated after make. Instead, Caffe2 will generate "libcaffe2.so" and "libcaffe2_gpu.so".

sudo find /usr -iname "libcaffe2*"
/usr/local/lib/libcaffe2.so
/usr/local/lib/libcaffe2_module_test_dynamic.so
/usr/local/lib/libcaffe2_gpu.so
/usr/local/lib/libCaffe2_GPU.so        <-- it's old version
/usr/local/lib/libCaffe2_CPU.so        <-- it's old version

**Comment by leonardvandriel** [comment]
thanks @teyenliu
